name: flutter_application_2_test_ui
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  uuid: ^4.2.1
  intl: ^0.18.1
  local_auth: ^2.1.7
  fl_chart: ^0.65.0
  file_picker: ^6.1.1
  flutter_local_notifications: ^16.2.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
